## DocGen

### Phases

The DocGen application runs using the following steps:

1. Scan the directory structure.
+
This makes a list of Teams with lists of Projects within.

2. Generate files.
+
In this phase we generate files (in AsciiDoc). Currently that includes:
+
* Project overview documentation

3. Convert documents to AsciiDoc.
+
In this phase we rack up all the AsciiDoc files and convert them to HTML. This will also create extra support files like CSS, javascript and images.

4. Generate index files.
+
We generate the index files needed for searching across the entire site.

5. Copy support files.
+
This will copy all generated support files to the target directory. This also includes the index files.

### Configuration file

The configuration file has the following properties.

.Example configuration file
[source,json]
----
{
  "indexGenerator": {
    "includeNavigation": true, <1>
    "includeSearch": true, <2>
    "footer": { <3>
      "copyright": "© 2025 Copyright",
      "link": {
        "name": "Zenodotus",
        "url": "https://github.com/IvoLimmen/Zenodotus"
      }
    }
  },
  "tableOfContent": "LEFT", <4>
  "numberedSections": "ON", <5>
  "sourceDirectory": "directory containing the source",
  "targetDirectory": "directory to write to"
}
----
<1> Either `true` or `false`. Will add a nice navigation bar on top.
<2> Either `true` or `false`. Will add a search option in the navigation bar on top. Can be without the navigation.
<3> Adding this part will show a nice footer at the bottom.
<4> Either `LEFT`, `RIGHT`, `PREAMBLE`, `AUTO` to enable table of content for all files, `OFF` to disable, or `AS_DEFINED` by adoc file.
<5> Either `ON` to enable numbered sections for all files, `OFF` to disable, or `AS_DEFINED` by adoc file.

### Running the DocGen application

Create a copy of the `docgen.json.template` file and call it `docgen.json` in the `docgen/config` directory.

.Running the application from the command line
[source,bash]
----
CONFIG_DIR=${PWD}/config mvn exec:java -pl :docgen-app
----

### Testing the generated site

When you want to test the features like searching you need to access the generated site using a webserver. 
You can open a terminal, go to the output directory you configured and run:

.Running a webserver using Python
[source,bash]
----
$ python3 -m http.server 8080
----

or:

.Running a webserver using PHP
[source,bash]
----
$ php -S localhost:8080
----

.Running a webserver using Node
[source,bash]
----
$ npm install -g node-static
$ static -p 8000
----

.Running a webserver using Java (Java 18+)
[source,bash]
----
$ jwebserver -d ${PWD}/output -b 0.0.0.0 -p 8080
----